languageCode = "en-us"
title = "Dimension"
baseurl = "http://example.org/"
theme = "dimension"

[params]
  title = "Dimension"
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[menu.main]]
  name = "Intro"
  weight = 10
  url = "#intro"
[[menu.main]]
  name = "Work"
  weight = 20
  url = "#work"
[[menu.main]]
  name = "About"
  weight = 30
  url = "#about"
[[menu.main]]
  name = "Contact"
  weight = 40
  url = "#contact"
[[menu.main]]
  name = "Elements"
  weight = 50
  url = "#elements"
[[menu.main]]
  name = "Formspree"
  weight = 60
  url = "#formspree"
